# Server
server.port=8082

# Database (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/hr_db
spring.datasource.username=hr_user
spring.datasource.password=hr_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# Redis (Upstash Cloud)
spring.data.redis.host=helping-labrador-22731.upstash.io
spring.data.redis.port=6379
spring.data.redis.password=AVjLAAIncDFjM2I3ZDI3OWIxNWU0OTMwOTcxMTQ3OWRjOTQ0MjNhNXAxMjI3MzE
spring.data.redis.ssl.enabled=true

# Kafka
spring.kafka.consumer.group-id=hr-service-group