# ===================================================================
# CONFIG RIÊNG CHO PHÂN HỆ NHÂN SỰ (HR-SERVICE)
# ===================================================================

server.port=8082

# Cấu hình kết nối Database PostgreSQL độc lập của HR
spring.datasource.url=jdbc:postgresql://localhost:5432/hr_db
spring.datasource.username=hr_user
spring.datasource.password=hr_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# Cấu hình bộ nhớ đệm Redis (Upstash Cloud) phục vụ lưu cache hồ sơ nhân viên
spring.data.redis.host=helping-labrador-22731.upstash.io
spring.data.redis.port=6379
spring.data.redis.password=AVjLAAIncDFjM2I3ZDI3OWIxNWU0OTMwOTcxMTQ3OWRjOTQ0MjNhNXAxMjI3MzE
spring.data.redis.ssl.enabled=true

# Định danh nhóm Consumer lắng nghe Kafka dành riêng cho HR
spring.kafka.consumer.group-id=hr-service-group