# Server
server.port=8083

# Database (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/report_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Logging
logging.level.com.report_service=DEBUG

# Kafka
spring.kafka.consumer.group-id=report-service-group