# ===================================================================
# CONFIG HẠ TẦNG DÙNG CHUNG TOÀN HỆ THỐNG (SHARED SERVICES)
# ===================================================================

# Kích hoạt tính năng Virtual Threads tối ưu hiệu năng xử lý đồng thời
spring.threads.virtual.enabled=true

# Khai báo địa chỉ tổng đài Service Discovery Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Địa chỉ Kafka Broker chung toàn app
spring.kafka.bootstrap-servers=localhost:9092

# Cấu hình kích hoạt cơ chế Migration Database mặc định cho toàn bộ các Service
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true