# Server
server.port=8084

# Database (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/account_identity_db
spring.datasource.username=postgres
spring.datasource.password=root_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Kafka
spring.kafka.consumer.group-id=identity-service-group